.TH TUM 1 "August 2025" "tum-bash" "User Commands"

.SH NAME
\fBtum\fR \- TheUnixManager written in GNU Bash.

.SH SYNOPSIS
.B tum
[\fIoptions\fR] <command> [arguments...]
.SH DESCRIPTION
\fBtum\fR (TheUnixManager) is a universal package management and system initialization library created by Archetypum,
designed to simplify interactions with UNIX-like operating systems and streamline the development of system-related
bash/shell scripts.

This is the Bash implementation of \fBtum\fR.

.SH OPTIONS
.TP
.B h, -h, --help
Show usage information.
.TP
.B c, -c, --commands
List all available commands.
.TP
.B v, -v, --version
Show the current version.

.SH GATHERING SYSTEM INFORMATION
.TP
.B tum get_distro 
Identifies and returns the current UNIX-like distribution name. 
Identifies most GNU, Linux, BSD, Apple, Android, Haiku, Minix distributions.
.TP
.B tum get_package_manager
Identifies and returns package manager available on the system.
Identifies apt, apt-get, aptitude, apk, dnf, dpkg, guix, homebrew, pkg, pkgin, pkg_add, pacman, yay, pamac, trizen, portage, qi, slackpkg, xbps-install, yum, zypper.
.TP
.B tum get_init_system
Identifies to identify the init system by checking known file paths and the name of PID 1.
Identifies systemd, sysvinit, openrc, runit, s6, dinit, launchd, GNU shepherd.
.TP
.B tum get_pid1_comm
Returns the COMM field for PID 1 using \fBps\fR utility.
.TP
.B tum check_privileges
Checks if user is root.

.SH EXIT STATUS
.TP
0
Success.
.TP
>0
An error occurred (invalid command or execution failure).

.SH ENVIRONMENT
.TP
.B LC_ALL, LANG
By default, \fBtum\fR sets \fILC_ALL=C\fR and \fILANG=C\fR to ensure
consistent and fast text processing.

.SH AUTHORS
Created by \fBArchetypum\fR

Currenty maintained by \fBKinderfeld\fR <\fIhttps://github.com/Kinderfeld\fR>

.SH COPYRIGHT
Copyright (C) 2025 Archetypum

\fBtum-bash\fR is free software: you can redistribute it and/or modify
it under the terms of the GNU Lesser General Public License as published by
the Free Software Foundation, either version 3 of the License, or
(at your option) any later version.

\fBtum-bash\fR is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU Lesser General Public License for more details.

You should have received a copy of the GNU Lesser General Public License
along with \fBtum-bash\fR.  If not, see <\fIhttps://www.gnu.org/licenses/\fR>.

.SH REPORTING BUGS
Project homepage: <\fIhttps://github.com/Archetypum/tum-bash\fR>

.SH SEE ALSO

\fBsh\fR(1), \fBash\fR(1), \fBdash\fR(1), \fBcsh\fR(1), \fBksh\fR(1), \fBbash\fR(1), \fBzsh\fR(1), \fBfish\fR(1)

\fBsystemd\fR(1), \fBsystemctl\fR(1), \fBinit\fR(1), \fBservice\fR(1), \fBopenrc\fR(1), \fBrc-service\fR(1), \fBs6-svc\fR(1), \fBs6-svscan\fR(1), \fBrunit\fR(1), \fBsv\fR(1), \fBdinit\fR(1), \fBdinitctl\fR(1), \fBlaunchd\fR(1), \fBlaunchctl\fR(1)

\fBapt\fR(1), \fBapt-get\fR(1), \fBaptitude\fR(1), \fBapk\fR(1), \fBapk\fR(1), \fBdpkg\fR(1), \fBguix\fR(1), \fBhomebrew\fR(1), \fBpkg\fR(1), \fBpkgin\fR(1), \fBpkg_add\fR(1), \fBpacman\fR(1), \fByay\fR(1), \fBpamac\fR(1), \fBtrizen\fR(1), \fBportage\fR(1), \fBqi\fR(1), \fBslackpkg\fR(1), \fBxbps-install\fR(1), \fByum\fR(1), \fBzypper\fR(1)
