.TH TUM 1 "August 2025" "tum-bash" "User Commands"

.SH NAME
\fBtum\fR \- TheUnixManager written in GNU Bash.

.SH SYNOPSIS
.B tum
[\fIoptions\fR] <command> [arguments...]
.SH DESCRIPTION
\fBtum\fR (TheUnixManager) is a universal package management and system initialization library created by Archetypum,
designed to simplify interactions with UNIX-like operating systems and streamline the development of system-related
bash/shell scripts.

This is the Bash implementation of \fBtum\fR.

.SH OPTIONS
.TP
.B -h, --help
Show usage information.
.TP
.B -c, --commands
List all available commands.
.TP
.B -v, --version
Show the current version.

.SH GATHERING SYSTEM INFORMATION
.TP
.B tum get_user_distro
Detects and returns the current UNIX-like distribution name.
Detects most GNU, Linux, BSD, Apple, Android, Haiku, Minix distributions.
.TP
.B tum get_init_system
Attempts to identify the init system by checking known file paths and the name of PID 1.
.TP
.B tum get_pid1_comm
Returns the COMM field for PID 1 using \fBps\fR utility.
.TP
.B tum check_privileges
Checks if user is root.

.SH EXIT STATUS
.TP
0
Success.
.TP
>0
An error occurred (invalid command or execution failure).

.SH ENVIRONMENT
.TP
.B LC_ALL, LANG
By default, \fBtum\fR sets \fILC_ALL=C\fR and \fILANG=C\fR to ensure
consistent and fast text processing.

.SH AUTHORS
Created by \fBArchetypum\fR

Currenty maintained by \fBKinderfeld\fR <\fIhttps://github.com/Kinderfeld\fR>

.SH COPYRIGHT
Copyright (C) 2025 Archetypum

\fBtum-bash\fR is free software: you can redistribute it and/or modify
it under the terms of the GNU Lesser General Public License as published by
the Free Software Foundation, either version 3 of the License, or
(at your option) any later version.

\fBtum-bash\fR is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU Lesser General Public License for more details.

You should have received a copy of the GNU Lesser General Public License
along with \fBtum-bash\fR.  If not, see <\fIhttps://www.gnu.org/licenses/\fR>.

.SH REPORTING BUGS
Project homepage: <\fIhttps://github.com/Archetypum/tum-bash\fR>

.SH SEE ALSO

\fBsh\fR(1), \fBash\fR(1), \fBdash\fR(1), \fBcsh\fR(1), \fBcsh\fR(1), \fBbash\fR(1), \fBzsh\fR(1), \fBfish\fR(1)
